// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDctepulKuEVTqMWuOl4QM9mNp2r4CJ1zM',
    appId: '1:985445046186:web:ac7d8986ed1faba9ebbdd3',
    messagingSenderId: '985445046186',
    projectId: 'faith-jivottama',
    authDomain: 'faith-jivottama.firebaseapp.com',
    storageBucket: 'faith-jivottama.firebasestorage.app',
    measurementId: 'G-L2S4WVTFX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAqN1n0dL1QDgwu3-DJ2aCtfyyNektgGY',
    appId: '1:985445046186:android:2fe0281c2c840483ebbdd3',
    messagingSenderId: '985445046186',
    projectId: 'faith-jivottama',
    storageBucket: 'faith-jivottama.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwwyisFabEeABQ0HEWZMLLa4SWyDsRh0Q',
    appId: '1:985445046186:ios:e221aee8d5ee2067ebbdd3',
    messagingSenderId: '985445046186',
    projectId: 'faith-jivottama',
    storageBucket: 'faith-jivottama.firebasestorage.app',
    androidClientId: '985445046186-8dpa4jap88tdd4ec7smghdieqm9pcurb.apps.googleusercontent.com',
    iosClientId: '985445046186-vfk32kvf9jjhlqg5icag0ibhf8fjfelc.apps.googleusercontent.com',
    iosBundleId: 'com.example.faithMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwwyisFabEeABQ0HEWZMLLa4SWyDsRh0Q',
    appId: '1:985445046186:ios:e221aee8d5ee2067ebbdd3',
    messagingSenderId: '985445046186',
    projectId: 'faith-jivottama',
    storageBucket: 'faith-jivottama.firebasestorage.app',
    androidClientId: '985445046186-8dpa4jap88tdd4ec7smghdieqm9pcurb.apps.googleusercontent.com',
    iosClientId: '985445046186-vfk32kvf9jjhlqg5icag0ibhf8fjfelc.apps.googleusercontent.com',
    iosBundleId: 'com.example.faithMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDctepulKuEVTqMWuOl4QM9mNp2r4CJ1zM',
    appId: '1:985445046186:web:64976b4e1e86de60ebbdd3',
    messagingSenderId: '985445046186',
    projectId: 'faith-jivottama',
    authDomain: 'faith-jivottama.firebaseapp.com',
    storageBucket: 'faith-jivottama.firebasestorage.app',
    measurementId: 'G-R02P2ZPW8E',
  );

}